attempting the shell function here

diff --git a/src/commands/notify_e2e_failure.yml b/src/commands/notify_e2e_failure.yml
--- a/src/commands/notify_e2e_failure.yml
+++ b/src/commands/notify_e2e_failure.yml
@@ -3,7 +3,29 @@ steps:
   - run:
       name: JQ install
       command: |
-        apk add jq
+              InstallJq() {
+                sex x+
+                if uname -a | grep Darwin > /dev/null 2>&1; then
+                echo "Checking For JQ + CURL: MacOS"
+                command -v jq >/dev/null 2>&1 || HOMEBREW_NO_AUTO_UPDATE=1 brew install jq --quiet
+                return $?
+
+                elif cat /etc/issue | grep Debian > /dev/null 2>&1 || cat /etc/issue | grep Ubuntu > /dev/null 2>&1; then
+                echo "Checking For JQ + CURL: Debian"
+                if [ "$(id -u)" = 0 ]; then export SUDO=""; else # Check if we're root
+                    export SUDO="sudo";
+                fi
+                command -v jq >/dev/null 2>&1 || { $SUDO apt -qq update && $SUDO apt -qq install -y jq; }
+                return $?
+
+                elif cat /etc/issue | grep Alpine > /dev/null 2>&1; then
+                echo "Checking For JQ + CURL: Alpine"
+                command -v curl >/dev/null 2>&1 || { echo >&2 "SLACK ORB ERROR: CURL is required. Please install."; exit 1; }
+                command -v jq >/dev/null 2>&1 || { echo >&2 "SLACK ORB ERROR: JQ is required. Please install"; exit 1; }
+                return $?
+                fi
+              }
+              InstallJq
       when: always
   - run:
       when: on_fail
